services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=short_links

  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=docker
